# Generated by Django 6.1 on 2026-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='can_request_quote',
            field=models.BooleanField(default=False),
        ),
    ]
