# Generated by Django 6.1 on 2026-09-03 12:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_can_request_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6)),
                ('can_request_quote', models.BooleanField(default=False)),
                ('can_enter_weight', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.customertariff'),
        ),
    ]
