# Generated by Django 6.1 on 2026-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password reset')], default='login', max_length=40),
        ),
    ]
