# Generated by Django 6.1 on 2026-09-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_password_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_identification_code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('company_official_name', models.CharField(max_length=255)),
                ('legal_address', models.TextField()),
                ('contact_first_name', models.CharField(max_length=120)),
                ('contact_last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('mobile_phone', models.CharField(db_index=True, max_length=40)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_profile', to='accounts.customer')),
            ],
            options={
                'ordering': ['company_official_name', 'company_identification_code'],
            },
        ),
    ]
