# Generated by Django 6.1 on 2026-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_legalentityprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password reset'), ('legal_entity_mobile', 'Legal entity mobile')], default='login', max_length=40),
        ),
    ]
