# Generated by Django 6.1 on 2026-09-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=40)),
                ('vin', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('full', '100% payment')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('action_required', 'Action required'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='payment_pending', max_length=40)),
                ('total_gel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_id', models.CharField(max_length=255)),
                ('quote_id', models.CharField(max_length=120)),
                ('part_option_id', models.CharField(max_length=120)),
                ('part_number', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('eta_days', models.PositiveIntegerField(blank=True, null=True)),
                ('final_price_gel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GEL', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
