# Generated by Django 6.1 on 2026-09-01 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='action_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='action_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='action_type',
            field=models.CharField(blank=True, choices=[('', 'No action'), ('price_change', 'Price change'), ('eta_change', 'ETA change'), ('weight_change', 'Weight/dimensions change'), ('fitment_issue', 'Fitment issue'), ('alternative_required', 'Alternative required'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_confirmed', 'Payment confirmed'), ('checking', 'Checking'), ('action_required', 'Action required'), ('purchased', 'Purchased'), ('received_usa', 'Received in USA'), ('shipped_to_georgia', 'Shipped to Georgia'), ('received_georgia', 'Received in Georgia'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('action_required', 'Action required'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='payment_pending', max_length=40),
        ),
    ]
