# Generated by Django 6.1 on 2026-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_orderitem_action_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='proposed_eta_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='proposed_final_price_gel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
