# Generated by Django 6.1 on 2026-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_proposed_eta_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='proposed_expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
