# Generated by Django 6.1 on 2026-09-02 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_expected_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('price_change_requested', 'Price change requested'), ('eta_change_requested', 'ETA change requested'), ('change_requested', 'Change requested'), ('action_resolved', 'Action resolved'), ('note_added', 'Note added')], db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('customer', 'Customer'), ('operator', 'Operator'), ('admin', 'Admin')], default='system', max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('visible_to_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
