# Generated by Django 6.1 on 2026-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
