# Generated by Django 6.1 on 2026-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer_notice_order_weight_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
