# Generated by Django 6.1 on 2026-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_customer_notice_orderitem_weight_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_notice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight_source',
        ),
    ]
