# Generated by Django 6.1 on 2026-09-10 08:11

from django.db import migrations

def normalize_phone(phone):
    digits = "".join(ch for ch in str(phone or "") if ch.isdigit())

    if digits.startswith("995"):
        digits = digits[3:]

    return digits


def link_orders_to_customers(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Customer = apps.get_model("accounts", "Customer")

    for order in Order.objects.filter(customer__isnull=True).iterator():
        customer = (
            Customer.objects.filter(session_id=order.session_id)
            .order_by("-is_phone_verified", "-updated_at", "-id")
            .first()
        )

        if not customer:
            phone = normalize_phone(order.customer_phone)
            phone_values = [order.customer_phone]

            if phone and phone not in phone_values:
                phone_values.append(phone)

            customer = (
                Customer.objects.filter(phone__in=phone_values)
                .order_by("-is_phone_verified", "-updated_at", "-id")
                .first()
            )

        if customer:
            order.customer_id = customer.id
            order.save(update_fields=["customer"])



class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_order_customer'),
    ]

    operations = [
        migrations.RunPython(link_orders_to_customers, migrations.RunPython.noop),
    ]
