# Generated by Django 6.1 on 2026-09-10 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_phoneverificationcode_purpose'),
        ('orders', '0015_backfill_order_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('legal_entity', 'Legal entity')], db_index=True, default='personal', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_company_identification_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_company_official_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_contact_first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_contact_last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_legal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_mobile_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.legalentityprofile'),
        ),
    ]
