# Generated by Django 6.1 on 2026-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_delivery_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
