# Generated by Django 6.1 on 2026-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_courier_delivery_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_delivery_action_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_delivery_action_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_delivery_fee_gel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_delivery_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proposed_courier_delivery_fee_gel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
