# Generated by Django 6.1 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight_source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
