# Generated by Django 6.1 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_carrierservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider', models.CharField(choices=[('demo', 'Demo'), ('amt', 'AutoMotoTrade')], db_index=True, max_length=30)),
                ('part_number', models.CharField(db_index=True, max_length=120)),
                ('vin', models.CharField(blank=True, max_length=40)),
                ('found_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('normalized_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
